//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lodas_Reader
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
    	public Entities(string connectionString) : base(connectionString){
    	    
    	}
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<u_lod_psd_festbezuege> u_lod_psd_festbezuege { get; set; }
        public DbSet<u_lod_psd_mitarbeiter> u_lod_psd_mitarbeiter { get; set; }
    
        public virtual int Update(Nullable<int> auto_lfd_nr, Nullable<int> bnr, Nullable<int> mnr, Nullable<int> pnr_psd, Nullable<short> festbez_id_psd, Nullable<int> akz_id, Nullable<short> lohnart_nr_psd, Nullable<decimal> betrag_psd, Nullable<short> intervall_psd, string gab_psd, Nullable<short> kz_monatslohn_psd, Nullable<short> kuerzung_psd)
        {
            var auto_lfd_nrParameter = auto_lfd_nr.HasValue ?
                new ObjectParameter("auto_lfd_nr", auto_lfd_nr) :
                new ObjectParameter("auto_lfd_nr", typeof(int));
    
            var bnrParameter = bnr.HasValue ?
                new ObjectParameter("bnr", bnr) :
                new ObjectParameter("bnr", typeof(int));
    
            var mnrParameter = mnr.HasValue ?
                new ObjectParameter("mnr", mnr) :
                new ObjectParameter("mnr", typeof(int));
    
            var pnr_psdParameter = pnr_psd.HasValue ?
                new ObjectParameter("pnr_psd", pnr_psd) :
                new ObjectParameter("pnr_psd", typeof(int));
    
            var festbez_id_psdParameter = festbez_id_psd.HasValue ?
                new ObjectParameter("festbez_id_psd", festbez_id_psd) :
                new ObjectParameter("festbez_id_psd", typeof(short));
    
            var akz_idParameter = akz_id.HasValue ?
                new ObjectParameter("akz_id", akz_id) :
                new ObjectParameter("akz_id", typeof(int));
    
            var lohnart_nr_psdParameter = lohnart_nr_psd.HasValue ?
                new ObjectParameter("lohnart_nr_psd", lohnart_nr_psd) :
                new ObjectParameter("lohnart_nr_psd", typeof(short));
    
            var betrag_psdParameter = betrag_psd.HasValue ?
                new ObjectParameter("betrag_psd", betrag_psd) :
                new ObjectParameter("betrag_psd", typeof(decimal));
    
            var intervall_psdParameter = intervall_psd.HasValue ?
                new ObjectParameter("intervall_psd", intervall_psd) :
                new ObjectParameter("intervall_psd", typeof(short));
    
            var gab_psdParameter = gab_psd != null ?
                new ObjectParameter("gab_psd", gab_psd) :
                new ObjectParameter("gab_psd", typeof(string));
    
            var kz_monatslohn_psdParameter = kz_monatslohn_psd.HasValue ?
                new ObjectParameter("kz_monatslohn_psd", kz_monatslohn_psd) :
                new ObjectParameter("kz_monatslohn_psd", typeof(short));
    
            var kuerzung_psdParameter = kuerzung_psd.HasValue ?
                new ObjectParameter("kuerzung_psd", kuerzung_psd) :
                new ObjectParameter("kuerzung_psd", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update", auto_lfd_nrParameter, bnrParameter, mnrParameter, pnr_psdParameter, festbez_id_psdParameter, akz_idParameter, lohnart_nr_psdParameter, betrag_psdParameter, intervall_psdParameter, gab_psdParameter, kz_monatslohn_psdParameter, kuerzung_psdParameter);
        }
    
        public virtual int Delete(Nullable<int> auto_lfd_nr)
        {
            var auto_lfd_nrParameter = auto_lfd_nr.HasValue ?
                new ObjectParameter("auto_lfd_nr", auto_lfd_nr) :
                new ObjectParameter("auto_lfd_nr", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete", auto_lfd_nrParameter);
        }
    }
}
