//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lodas_Reader
{
    using System;
    using System.Collections.Generic;
    
    public partial class u_lod_psd_mitarbeiter
    {
        public u_lod_psd_mitarbeiter()
        {
            this.u_lod_psd_festbezuege = new HashSet<u_lod_psd_festbezuege>();
        }
    
        public int bnr { get; set; }
        public int mnr { get; set; }
        public int pnr_psd { get; set; }
        public string duevo_familienname_psd { get; set; }
        public string duevo_vorname_psd { get; set; }
        public string duevo_titel_psd { get; set; }
        public string duevo_namenszusatz_psd { get; set; }
        public string duevo_vorsatzwort_psd { get; set; }
        public string adresse_strasse_psd { get; set; }
        public string adresse_plz_psd { get; set; }
        public string adresse_ort_psd { get; set; }
        public string adresse_nation_kz_psd { get; set; }
        public Nullable<short> adressart_psd { get; set; }
        public string adresse_anschriftenzusatz_psd { get; set; }
        public string geburtsdatum_ttmmjj_psd { get; set; }
        public string geschlecht_psd { get; set; }
        public string sozialversicherung_nr_psd { get; set; }
        public string familienstand_psd { get; set; }
        public Nullable<short> staatsangehoerigkeit_psd { get; set; }
        public string schwerbeschaedigt_psd { get; set; }
        public Nullable<System.DateTime> ersteintrittsdatum_psd { get; set; }
        public string beschaeft_ende_kz_psd { get; set; }
        public string ebz_nach_austritt_kz_psd { get; set; }
        public Nullable<short> vorweg_abr_abruf_termin_kz_psd { get; set; }
        public string probeabrechnung_kz_rzk { get; set; }
        public string einzelabrechnung_kz_rzk { get; set; }
        public string eur_versnr_psd { get; set; }
        public string vorsatzwort_gebname_psd { get; set; }
        public string gebname_psd { get; set; }
        public string nazu_gebname_psd { get; set; }
        public string gebort_psd { get; set; }
        public Nullable<short> geburtsland_psd { get; set; }
        public Nullable<int> akz_id { get; set; }
        public Nullable<System.DateTime> arbeitserlaubnis_psd { get; set; }
        public Nullable<System.DateTime> aufenthaltserlaubnis_psd { get; set; }
        public Nullable<System.DateTime> datum_studienbesch_psd { get; set; }
        public Nullable<System.DateTime> sba_ausbildungsbeginn_psd { get; set; }
        public Nullable<System.DateTime> sba_ausbildungsende_psd { get; set; }
        public string ma_gruppe_psd { get; set; }
        public Nullable<short> kz_subtables { get; set; }
        public string adresse_plz_ausland_psd { get; set; }
        public string pnr_betriebliche_psd { get; set; }
        public Nullable<System.DateTime> abrechnung_stand_rzk { get; set; }
        public Nullable<short> abrechnungsart_rzk { get; set; }
        public string loesch_nach_austr_unterdr_psd { get; set; }
        public string ma_guid_psd { get; set; }
        public string storno_sofortmeldung_psd { get; set; }
        public string adresse_strassenname_psd { get; set; }
        public string adresse_strasse_nr_psd { get; set; }
        public string email_psd { get; set; }
        public Nullable<short> ausscheiden_ruhestand_psd { get; set; }
        public string verw_ersteintr_elena_bn_psd { get; set; }
        public Nullable<System.DateTime> abw_eintritt_sofortmeldung_psd { get; set; }
        public Nullable<System.DateTime> datum_tod_psd { get; set; }
        public Nullable<short> mitarbeitertyp_psd { get; set; }
        public Nullable<decimal> abw_mindlohn_psd { get; set; }
        public Nullable<short> unterdr_mindlohnpruef_psd { get; set; }
        public string kz_aend_festbez_psd { get; set; }
    
        public virtual ICollection<u_lod_psd_festbezuege> u_lod_psd_festbezuege { get; set; }
    }
}
