//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lodas_Reader
{
    using System;
    using System.Collections.Generic;
    
    public partial class u_lod_psd_festbezuege
    {
        public int bnr { get; set; }
        public int mnr { get; set; }
        public int pnr_psd { get; set; }
        public Nullable<int> akz_id { get; set; }
        public Nullable<short> lohnart_nr_psd { get; set; }
        public Nullable<decimal> betrag_psd { get; set; }
        public Nullable<short> intervall_psd { get; set; }
        public string gab_psd { get; set; }
        public Nullable<short> kz_monatslohn_psd { get; set; }
        public int auto_lfd_nr { get; set; }
        public short festbez_id_psd { get; set; }
        public Nullable<short> kuerzung_psd { get; set; }
    
        public virtual u_lod_psd_mitarbeiter u_lod_psd_mitarbeiter { get; set; }
    }
}
